### ISSUE TITLE
Idea integration with bucket?

### ISSUE THREAD

**Issue by bolzobrazil** [coracle-social/bucket#3]
Hi would these ideas be integrateable with bucket?
https://github.com/nostr-protocol/nostr/issues/194
https://www.reddit.com/r/TOR/comments/1e4te8m/introducing_discussing_reflectors_as_concept/
https://lists.torproject.org/pipermail/tor-relays/2024-July/021744.htm**

**Comment by staab** [comment]
It's not a bad idea, but not a goal for this project. Feel free to fork!
